apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: fleet-manager
  namespace: argocd
spec:
  description: Fleet Manager Cluster Project
  sourceRepos:
    - 'https://github.com/argoproj/argo-helm'
    - 'https://github.com/grafana/helm-charts'
    - 'https://prometheus-community.github.io/helm-charts'
    - 'https://grafana.github.io/helm-charts'
    - 'http://gitea.test/andreas/argo.git'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
    - namespace: '*'
      server: https://10.100.0.2:6443
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: 'apps'
      kind: Deployment
    - group: 'apps'
      kind: StatefulSet
    - group: 'apps'
      kind: DaemonSet
    - group: ''
      kind: Service
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
    - group: 'networking.k8s.io'
      kind: Ingress
    - group: 'networking.k8s.io'
      kind: IngressRoute
  namespaceResourceWhitelist:
    - group: ''
      kind: '*'
    - group: 'apps'
      kind: '*'
    - group: 'networking.k8s.io'
      kind: '*'
    - group: 'monitoring.coreos.com'
      kind: '*'
