apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fleet-manager-app-of-apps
  namespace: argocd
spec:
  project: fleet-manager
  source:
    repoURL: http://gitea.test/andreas/argo.git
    targetRevision: HEAD
    path: applications/fleet-manager
    directory:
      include: "*.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
