apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cli-api
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: fleet-manager
  source:
    repoURL: https://github.com/qubeio/tha-argocd.git
    targetRevision: HEAD
    path: manifests/cli-api
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
