apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: fleet-manager
  source:
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.16.2
    chart: external-secrets
    helm:
      parameters:
        - name: installCRDs
          value: "true"
        - name: resources.limits.cpu
          value: "200m"
        - name: resources.limits.memory
          value: "256Mi"
        - name: resources.requests.cpu
          value: "50m"
        - name: resources.requests.memory
          value: "64Mi"
        - name: webhook.resources.limits.cpu
          value: "100m"
        - name: webhook.resources.limits.memory
          value: "128Mi"
        - name: webhook.resources.requests.cpu
          value: "25m"
        - name: webhook.resources.requests.memory
          value: "32Mi"
        - name: certController.resources.limits.cpu
          value: "100m"
        - name: certController.resources.limits.memory
          value: "128Mi"
        - name: certController.resources.requests.cpu
          value: "25m"
        - name: certController.resources.requests.memory
          value: "32Mi"
        - name: securityContext.runAsNonRoot
          value: "true"
        - name: securityContext.runAsUser
          value: "65534"
        - name: webhook.securityContext.runAsNonRoot
          value: "true"
        - name: webhook.securityContext.runAsUser
          value: "65534"
        - name: certController.securityContext.runAsNonRoot
          value: "true"
        - name: certController.securityContext.runAsUser
          value: "65534"
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
