apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      targetRevision: 7.0.0
      chart: grafana
      helm:
        valueFiles:
          - $values/argo/applications/fleet-manager/values/grafana/ingress.yaml
          - $values/argo/applications/fleet-manager/values/grafana/auth.yaml
          - $values/argo/applications/fleet-manager/values/grafana/datasources.yaml
    - repoURL: https://github.com/qubeio/tha-argocd.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
