apiVersion: v1
kind: Secret
metadata:
  name: github-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/qubeio/tha-argocd.git
  name: github-argo-repo
  # GitHub uses HTTPS, so no insecure flag needed
  # insecure: "false"
