apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vclusters
  namespace: argocd
spec:
  project: fleet-manager
  source:
    repoURL: https://github.com/qubeio/tha-argocd.git
    targetRevision: HEAD
    path: platforms
    directory:
      # Include all YAML files in platforms/ directory
      include: "*.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
