apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcluster-nprod1
  namespace: argocd
spec:
  project: fleet-manager
  source:
    repoURL: https://charts.loft.sh
    targetRevision: "*"
    chart: vcluster
    helm:
      releaseName: nprod1
      valuesObject:
        # Control plane configuration
        controlPlane:
          distro:
            k8s:
              enabled: true
              image:
                registry: ghcr.io
                repository: loft-sh/kubernetes
                tag: v1.33.4
              resources:
                limits:
                  cpu: 1000m
                  memory: 1Gi
                requests:
                  cpu: 100m
                  memory: 128Mi
          # Storage configuration - moved to correct location
          statefulSet:
            persistence:
              volumeClaim:
                size: 5Gi
          # Service configuration - moved to correct location
          service:
            spec:
              type: ClusterIP
        # Sync configuration - from host to vcluster
        sync:
          fromHost:
            nodes:
              enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: vcluster-nprod1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
