apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcluster-prod1
  namespace: argocd
spec:
  project: fleet-manager
  source:
    repoURL: https://charts.loft.sh
    targetRevision: *
    chart: vcluster
    helm:
      releaseName: prod1
      valuesObject:
        # Control plane configuration
        controlPlane:
          distro:
            k8s:
              enabled: true
              image:
                registry: ghcr.io
                repository: loft-sh/kubernetes
                tag: v1.33.4
                imagePullPolicy: IfNotPresent
              resources:
                limits:
                  cpu: 1000m
                  memory: 1Gi
                requests:
                  cpu: 100m
                  memory: 128Mi
        # Sync configuration - from host to vcluster
        sync:
          fromHost:
            nodes:
              enabled: true
            persistentVolumes:
              enabled: true
        # Storage configuration
        storage:
          size: 5Gi
        # Service configuration
        service:
          type: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: vcluster-prod1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
