apiVersion: v1
data:
  dynamic.yaml: |+
    tls:
      certificates:
        - certFile: "/etc/certs/tls.crt"
          keyFile: "/etc/certs/tls.key"

kind: ConfigMap
metadata:
  name: traefik-dynamic-config
  namespace: traefik
