apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: akeyless-secrets
spec:
  provider:
    akeyless:
      akeylessGWApiURL: "https://vault.akeyless.io"
      authSecretRef:
        secretRef:
          accessID:
            name: akeyless-credentials
            key: access-id
            namespace: external-secrets-system
          accessType:
            name: akeyless-credentials
            key: access-type
            namespace: external-secrets-system
          accessTypeParam:
            name: akeyless-credentials
            key: access-key
            namespace: external-secrets-system
---
apiVersion: v1
kind: Secret
metadata:
  name: akeyless-credentials
  namespace: external-secrets-system
type: Opaque
data:
  # Base64 encoded Akeyless credentials
  # Replace with your actual Akeyless credentials
  # access-id: <base64-encoded-access-id>
  # access-type: <base64-encoded-access-type> (e.g., "access_key")
  # access-key: <base64-encoded-access-key>
  access-id: ""
  access-type: ""
  access-key: ""