apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: homelab-test
  namespace: default
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: akeyless-secrets
    kind: ClusterSecretStore
  target:
    name: homelab-test
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/name: homelab-test
          app.kubernetes.io/component: homelab-test
  data:
    - secretKey: homelab-tester
      remoteRef:
        key: /homelab/homelab-tester
        property: homelab-tester
