apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    # Let's Encrypt staging server (for testing)
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: andreas@frangopoulos.co.uk # Your email for Let's Encrypt
    privateKeySecretRef:
      name: letsencrypt-staging-key
    solvers:
      - dns01:
          azureDNS:
            clientID: c7725ce7-c99b-422a-86b2-900e1726f3ae
            clientSecretSecretRef:
              name: azure-dns-credentials
              key: client-secret
            subscriptionID: e8df3063-b677-4cb3-beb0-b1a1b542ec93
            tenantID: f00d62a0-22a5-4ba4-9808-02e8228f5145
            resourceGroupName: titusglobal
            hostedZoneName: frang.uk
            # Use Azure DNS zone resource group
            environment: AzurePublicCloud
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Let's Encrypt production server
    server: https://acme-v02.api.letsencrypt.org/directory
    email: andreas@frangopoulos.co.uk # Your email for Let's Encrypt
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
      - dns01:
          azureDNS:
            clientID: c7725ce7-c99b-422a-86b2-900e1726f3ae
            clientSecretSecretRef:
              name: azure-dns-credentials
              key: client-secret
            subscriptionID: e8df3063-b677-4cb3-beb0-b1a1b542ec93
            tenantID: f00d62a0-22a5-4ba4-9808-02e8228f5145
            resourceGroupName: titusglobal
            hostedZoneName: frang.uk
            # Use Azure DNS zone resource group
            environment: AzurePublicCloud
