# Example: Create a Key Vault Secret
# This resource reads from a Kubernetes Secret and syncs it TO Azure Key Vault
# 
# Prerequisites:
# 1. Apply the source secret: kubectl apply -f example-k8s-secret.yaml
# 2. Ensure the Key Vault exists (see qubeio-vault resource below)
#
# Data flow: Kubernetes Secret → Crossplane → Azure Key Vault
apiVersion: keyvault.azure.upbound.io/v1beta1
kind: Secret
metadata:
  name: example-keyvault-secret
  namespace: crossplane-system
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    crossplane.io/external-name: example-secret
spec:
  forProvider:
    name: example-secret
    keyVaultIdSelector:
      matchLabels:
        keyvault: qubeio
    valueSecretRef:
      name: example-secret-value
      namespace: crossplane-system
      key: value
    contentType: "text/plain"
  providerConfigRef:
    name: default
---
# Example: Reference an existing Key Vault
# Note: You'll need to import or create the Key Vault resource first
apiVersion: keyvault.azure.upbound.io/v1beta2
kind: Vault
metadata:
  name: qubeio-vault
  namespace: crossplane-system
  labels:
    keyvault: qubeio
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    crossplane.io/external-name: qubeio
spec:
  forProvider:
    location: northeurope
    resourceGroupNameSelector:
      matchLabels:
        resourcegroup: qubeio
    skuName: standard
    tenantId: "${AZURE_TENANT_ID}"
    accessPolicy:
      - tenantId: "${AZURE_TENANT_ID}"
        objectId: "${AZURE_CLIENT_OBJECT_ID}"
        keyPermissions:
          - Get
          - List
          - Create
          - Update
        secretPermissions:
          - Get
          - List
          - Set
          - Delete
        certificatePermissions:
          - Get
          - List
  providerConfigRef:
    name: default
  managementPolicies:
    - "Observe"

