apiVersion: azure.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  credentials:
    source: Secret
    secretRef:
      name: azure-keyvault-crossplane-creds
      namespace: crossplane-system
      key: credentials

