apiVersion: azure.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  subscriptionID: e8df3063-b677-4cb3-beb0-b1a1b542ec93
  credentials:
    source: Secret
    secretRef:
      name: azure-keyvault-crossplane-creds
      namespace: crossplane-system
      key: credentials

