# CompositeResourceDefinition for Kind Clusters with Argo CD Integration
#
# This XRD defines a high-level API for creating Kind clusters
# that are automatically registered with Argo CD.
#
# Your provider's Cluster resource:
#   apiVersion: core.kind.crossplane.io/v1alpha1
#   kind: Cluster
#   spec.forProvider.name: cluster name
#   status.atProvider.status: cluster status
#   status.atProvider.endpoint: API server URL
#   status.atProvider.homelabIp: homelab IP address
#
# Usage:
#   kubectl apply -f xrd.yaml
#   kubectl apply -f composition.yaml
#   kubectl apply -f claim.yaml
---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xkindclusters.composed.kind.crossplane.io
spec:
  group: composed.kind.crossplane.io
  names:
    kind: XKindCluster
    plural: xkindclusters
  claimNames:
    kind: KindCluster
    plural: kindclusters
  
  # Support both cluster-scoped (XR) and namespace-scoped (Claim) usage
  connectionSecretKeys:
    - kubeconfig
    - endpoint
    - server
  
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                # User inputs
                parameters:
                  type: object
                  properties:
                    name:
                      type: string
                      description: "Name of the Kind cluster to create (spec.forProvider.name)"
                    
                    # Argo CD integration
                    argocd:
                      type: object
                      description: "Argo CD registration configuration"
                      properties:
                        enabled:
                          type: boolean
                          description: "Register cluster with Argo CD"
                          default: true
                        
                        namespace:
                          type: string
                          description: "Namespace where Argo CD is installed"
                          default: "argocd"
                        
                        clusterLabels:
                          type: object
                          description: "Labels to add to Argo CD cluster secret"
                          additionalProperties:
                            type: string
                        
                        project:
                          type: string
                          description: "Argo CD project for this cluster"
                          default: "default"
                  
                  required:
                    - name
                
                # Standard Crossplane composition selector
                compositionSelector:
                  type: object
                  properties:
                    matchLabels:
                      type: object
                      additionalProperties:
                        type: string
                
                compositionRef:
                  type: object
                  properties:
                    name:
                      type: string
            
            status:
              type: object
              properties:
                # Cluster status information
                clusterStatus:
                  type: string
                  description: "Status of the Kind cluster"
                
                endpoint:
                  type: string
                  description: "Kubernetes API endpoint"
                
                homelabIp:
                  type: string
                  description: "Homelab network IP address (10.100.201.x)"
                
                argocdRegistered:
                  type: boolean
                  description: "Whether cluster is registered with Argo CD"
      
      # Additional printer columns for kubectl get
      additionalPrinterColumns:
        - name: Cluster-Name
          type: string
          jsonPath: .spec.parameters.name
        - name: Status
          type: string
          jsonPath: .status.clusterStatus
        - name: Endpoint
          type: string
          jsonPath: .status.endpoint
        - name: Homelab-IP
          type: string
          jsonPath: .status.homelabIp
        - name: ArgoCD
          type: boolean
          jsonPath: .status.argocdRegistered
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
